package manifest

import (
	"bytes"
	"encoding/base64"
	"encoding/json"
	"os"
	"path/filepath"
	"testing"
)

// TestCanonicalJSON_MatchesPythonFixtures is the cross-language
// byte-for-byte check required by SPEC-06.
//
// The fixture file is generated by:
//
//	python updater/internal/manifest/gen_fixtures.py
//
// It contains {input, canonical_b64} pairs; canonical_b64 is what
// Python's workstation_agent.security.signature.canonical_json emits.
// Our Go CanonicalJSON must produce the identical bytes.
func TestCanonicalJSON_MatchesPythonFixtures(t *testing.T) {
	raw, err := os.ReadFile(filepath.Join("testdata", "canonical.json"))
	if err != nil {
		t.Fatalf("read fixture: %v", err)
	}
	var fixtures []struct {
		Input        any    `json:"input"`
		CanonicalB64 string `json:"canonical_b64"`
	}
	dec := json.NewDecoder(bytes.NewReader(raw))
	dec.UseNumber()
	if err := dec.Decode(&fixtures); err != nil {
		t.Fatalf("parse fixture: %v", err)
	}
	if len(fixtures) == 0 {
		t.Fatal("no fixtures loaded")
	}
	for i, f := range fixtures {
		want, err := base64.StdEncoding.DecodeString(f.CanonicalB64)
		if err != nil {
			t.Fatalf("fixture[%d]: bad base64: %v", i, err)
		}
		got, err := CanonicalJSON(f.Input)
		if err != nil {
			t.Fatalf("fixture[%d]: CanonicalJSON err: %v", i, err)
		}
		if string(got) != string(want) {
			t.Errorf("fixture[%d] mismatch\n  want: %s\n   got: %s", i, want, got)
		}
	}
}

func TestParse_RejectsUnknownFields(t *testing.T) {
	raw := []byte(`{"version":"1.2.3","channel":"stable","released_at":"","mandatory":false,"notes_url":"","artifacts":{"agent":{"url":"","sha256":"","size":1},"updater":{"url":"","sha256":"","size":1}},"min_updater_version":"1.0.0","extra":"nope"}`)
	if _, err := Parse(raw); err == nil {
		t.Fatal("expected error for unknown field")
	}
}

func TestParse_Roundtrip(t *testing.T) {
	raw := []byte(`{"version":"1.2.3","channel":"stable","released_at":"2026-09-15T04:00:00Z","mandatory":false,"notes_url":"https://x","artifacts":{"agent":{"url":"https://a","sha256":"aa","size":1},"updater":{"url":"https://u","sha256":"bb","size":2}},"min_updater_version":"1.0.0"}`)
	m, err := Parse(raw)
	if err != nil {
		t.Fatalf("parse: %v", err)
	}
	if m.Version != "1.2.3" || m.Artifacts.Agent.URL != "https://a" {
		t.Fatalf("bad parse: %+v", m)
	}
}

func TestParseVersion_EdgeCases(t *testing.T) {
	cases := []struct {
		in  string
		ok  bool
		maj int
	}{
		{"1.2.3", true, 1},
		{"10.20.30", true, 10},
		{"1.2.10", true, 1},
		{"1.2.3-beta.1", true, 1},
		{"1.2.3+build.5", true, 1},
		{"1.2", false, 0},
		{"a.b.c", false, 0},
		{"", false, 0},
	}
	for _, tc := range cases {
		m, _, _, err := ParseVersion(tc.in)
		if tc.ok && err != nil {
			t.Errorf("ParseVersion(%q): unexpected err %v", tc.in, err)
			continue
		}
		if !tc.ok && err == nil {
			t.Errorf("ParseVersion(%q): expected err", tc.in)
			continue
		}
		if tc.ok && m != tc.maj {
			t.Errorf("ParseVersion(%q): maj=%d want %d", tc.in, m, tc.maj)
		}
	}
}

func TestIsNewer_NumericCompare(t *testing.T) {
	cases := []struct {
		a, b string
		want bool
	}{
		{"1.2.10", "1.2.9", true},  // <- SPEC callout: string compare would fail here
		{"1.2.9", "1.2.10", false},
		{"2.0.0", "1.99.99", true},
		{"1.2.3", "1.2.3", false},
		{"0.1.0", "0.0.99", true},
	}
	for _, tc := range cases {
		got, err := IsNewer(tc.a, tc.b)
		if err != nil {
			t.Errorf("IsNewer(%q,%q) err: %v", tc.a, tc.b, err)
			continue
		}
		if got != tc.want {
			t.Errorf("IsNewer(%q,%q) = %v want %v", tc.a, tc.b, got, tc.want)
		}
	}
}
